apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/portfolio_perso"
  PORT: "3000"
  CLIENT_ORIGIN: "http://localhost"
  NODE_ENV: "production"
